### ISSUE TITLE
[Review Tools] Selection background makes text unreadable

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-code-manager#1951]
webpack://src/refractor/prism.css
prism.css: 56-64
```css
pre[class*="language-"]::-moz-selection, pre[class*="language-"] ::-moz-selection,
code[class*="language-"]::-moz-selection, code[class*="language-"] ::-moz-selection {
	background: #073642; /* base02 */
}

pre[class*="language-"]::selection, pre[class*="language-"] ::selection,
code[class*="language-"]::selection, code[class*="language-"] ::selection {
	background: #073642; /* base02 */
}
```

![image](https://user-images.githubusercontent.com/6458876/117573127-80d24880-b0eb-11eb-8c46-a1bdec83e3f2.png)
