### ISSUE TITLE
Convert common border styles to a Sass mixin

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#910]
**For QA**: Please check for regressions in the visual styling of all panel borders

Code manager uses these two common css rules for all borders:

```css
.example {
  border: 1px solid $light-gray;
  border-radius: $border-radius;
}
```

Let's move that to a [Sass mixin](https://sass-lang.com/documentation/at-rules/mixin) so that it can be replaced by:

```css
@include border-style();
```

Here is a real world example of [defining a mixin](https://github.com/mozilla/addons-frontend/blob/0541478615fab000c50fa703271e378d8fb7cfcb/src/core/css/inc/mixins.scss#L3) and [using it](https://github.com/mozilla/addons-frontend/blob/e1d2c4001131c9105ae349796558fce60124e09a/src/amo/pages/CategoriesPage/styles.scss#L4).
